name: Release Service

on:
  push:
    tags:
      - "*.*.*"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Extract branch name
      uses: vazco/github-actions-branch-name@v1
      id: branch

    - id: string
      uses: ASzc/change-string-case-action@v1
      with:
        string: ${{ github.event.repository.name }}
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.*

    - name: Get current time
      uses: MyJetTools/get-current-time@v2
      id: current-time
      with:
        format: YYYY-MM-DD HH:mm:ss
        utcOffset: "+00:00"

    - name: Build
      run: dotnet build --configuration Release /p:AssemblyVersion=${GITHUB_REF#refs/tags/}
    - name: Test
      run: dotnet test --no-build --configuration Release
    - name: ls
      run: ls

    - name: Publish Service
      run: dotnet publish ./src/${{ github.event.repository.name }}/${{ github.event.repository.name }}.csproj --configuration Release /p:AssemblyVersion=${GITHUB_REF#refs/tags/} --output ./publish-api

    - name: Check Service dir
      run: ls ./publish-api

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/tags/})"
      id: extract_branch

    - name: Publish image ST
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.MBOX_REGISTRY_USER }}
        password: ${{ secrets.MBOX_REGISTRY_PASS }}
        path: ./publish-api
        registry: ${{ secrets.MBOX_REGISTRY_URL }}
        repository: marketingbox/${{ steps.string.outputs.lowercase }}
        tag_with_ref: true
        build_args: app_version=${{ steps.string.outputs.lowercase }}:${{ steps.extract_branch.outputs.branch }},app_compilation_date=${{ steps.current-time.outputs.formattedTime }}


  update_version_master:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Extract branch name
      uses: vazco/github-actions-branch-name@v1
      id: branch

    - id: string
      uses: ASzc/change-string-case-action@v1
      with:
        string: ${{ github.event.repository.name }}
    - name: get master kube yamls
      uses: actions/checkout@v2
      with:
        repository: MyJetMarketingBox/marketing-box-kubernates-infrastructure
        ref: master
        token: ${{ secrets.UAT_GIT_TOKEN }}
    - run: |
        pattern=${{ steps.string.outputs.lowercase }}:.*$
        imagename=${{ steps.string.outputs.lowercase }}:${GITHUB_REF#refs/tags/}
        reg=$"s/${pattern}/${imagename}/g"
        echo $reg
        find . -type f -name "deployment.*" -print0 -exec sed -i -r $reg {} \;
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -a -m "Update version of service ${{ steps.string.outputs.lowercase }}"
        git push
